# Datos de conexion con el router MikroTik.
# Lo escribe la ventana 'Conexion y llaves SSH', pero se puede
# editar a mano con cualquier editor de texto.
ip = 192.168.88.1
usuario = admin
llave = /home/topicos/.ssh/mikrotik_tea_key
